using System.Globalization;
using LuSplit.Application.Models;

namespace LuSplit.Infrastructure.Export;

internal sealed class PdfTripExporter
{
    public async Task<ExportFileResult> ExportAsync(ExportTripDto dto, CancellationToken ct)
    {
        var lines = BuildLines(dto);
        var pdfBytes = SimplePdfBuilder.Build(lines);

        var slug = ExportFileNaming.Slug(dto.TripName, dto.ExportedAt);
        var fileName = $"{slug}-summary.pdf";
        var filePath = Path.Combine(dto.OutputDirectory, fileName);

        await File.WriteAllBytesAsync(filePath, pdfBytes, ct);
        return new ExportFileResult(filePath, fileName, "application/pdf");
    }

    private static IReadOnlyList<PdfLine> BuildLines(ExportTripDto dto)
    {
        var o = dto.Overview;
        var byId = o.Participants.ToDictionary(p => p.Id, p => p.Name, StringComparer.Ordinal);
        var currency = o.Group.Currency;
        var lines = new List<PdfLine>();

        // ── Header ──────────────────────────────────────────────
        lines.Add(new PdfLine(dto.TripName, PdfLineStyle.Title));
        var exportDate = DateTimeOffset.TryParse(dto.ExportedAt, null,
            DateTimeStyles.None, out var dt)
            ? dt.UtcDateTime.ToString("MMMM d, yyyy", CultureInfo.InvariantCulture)
            : dto.ExportedAt;
        lines.Add(new PdfLine($"Exported on {exportDate}", PdfLineStyle.Muted));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Separator));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));

        // ── Friends ─────────────────────────────────────────────
        lines.Add(new PdfLine("Friends", PdfLineStyle.Heading));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
        foreach (var p in o.Participants.OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
            lines.Add(new PdfLine($"  {p.Name}", PdfLineStyle.Normal));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Separator));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));

        // ── Balances / Settle up ─────────────────────────────────
        lines.Add(new PdfLine("Balances", PdfLineStyle.Heading));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
        var settlements = o.SettlementByParticipant.Transfers;
        if (settlements.Count == 0)
        {
            lines.Add(new PdfLine("Everyone is even. Nothing to settle.", PdfLineStyle.Normal));
        }
        else
        {
            foreach (var t in settlements)
            {
                var from = byId.GetValueOrDefault(t.FromParticipantId, t.FromParticipantId);
                var to = byId.GetValueOrDefault(t.ToParticipantId, t.ToParticipantId);
                lines.Add(new PdfLine($"  {from} owes {to}   {FormatMoney(t.AmountMinor, currency)}", PdfLineStyle.Normal));
            }
        }
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Separator));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));

        // ── Expenses ─────────────────────────────────────────────
        lines.Add(new PdfLine("Expenses", PdfLineStyle.Heading));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
        if (o.Expenses.Count == 0)
        {
            lines.Add(new PdfLine("No expenses recorded.", PdfLineStyle.Normal));
        }
        else
        {
            foreach (var e in o.Expenses.OrderBy(e => e.Date, StringComparer.Ordinal))
            {
                var paidBy = byId.GetValueOrDefault(e.PaidByParticipantId, e.PaidByParticipantId);
                lines.Add(new PdfLine($"  {e.Title}", PdfLineStyle.Normal));
                lines.Add(new PdfLine(
                    $"  {paidBy} paid {FormatMoney(e.AmountMinor, currency)}  \u2022  {FormatDate(e.Date)}",
                    PdfLineStyle.Muted));
                if (!string.IsNullOrWhiteSpace(e.Notes))
                    lines.Add(new PdfLine($"  {e.Notes}", PdfLineStyle.Muted));
                lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
            }
        }

        // ── Footer ───────────────────────────────────────────────
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Separator));
        lines.Add(new PdfLine(string.Empty, PdfLineStyle.Empty));
        lines.Add(new PdfLine("Generated by LuSplit", PdfLineStyle.Muted));

        return lines;
    }

    private static string FormatMoney(long minor, string currency)
        => $"{currency} {(minor / 100m).ToString("0.00", CultureInfo.InvariantCulture)}";

    private static string FormatDate(string isoDate)
    {
        if (DateTimeOffset.TryParse(isoDate, null, DateTimeStyles.None, out var dt))
            return dt.ToString("MMM d", CultureInfo.InvariantCulture);
        return isoDate;
    }
}
